/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique;

import base_de_donnée.ResultSetTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Frida
 */
public class Acceuiladmin extends javax.swing.JFrame {

    private Connection q;
    private Depot da;
    private Pret pa;
    
    Connection con = null;
    Statement st = null;
    ResultSet re = null;
    java.util.Date naissances;
    java.sql.Date mynaissance;
    java.sql.Connection connection = null;
    java.sql.Connection connections = null;
    String host="localhost";
    String port="5433";
    String db_name="association";
    String username="postgres";
    String password="root";
    boolean vrai = false;
     Transaction transactionFrame;
    Acceuilpretetrembourcement pretrembourseFrame;
    Connection connectionFrame;
    Resultset rs;
   
    public Acceuiladmin() {
        initComponents();
       Table();
       /* try {
            Class.forName("org.postgresql.Driver");
            connection =  DriverManager.getConnection("jdbc:postgresql://"+host+":"+port+"/"+db_name+"", ""+username+"", ""+password+"");
            Statement adds = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sql = "SELECT(id_membre,num_compte,passwords,nom_membre,prenom_membre,date_naiss,num_cni,etat_civil,personne_a_contacter,genre,statut) FROM membre";
                    
                 ResultSet r = adds.executeQuery(sql);
             ResultSetTableModel model = new ResultSetTableModel(r);
            
            
                 TableModel tableModel = jTable1.getModel();
                 int rowCount = model.getRowCount();
                 int columnCount = model.getColumnCount();
                     
                 System.out.println("columnCount = "+columnCount);
           for(int i = 0; i < rowCount; i++){
                for(int k = 0; k < columnCount   ; k++){
                    String rowValue = model.getValueAt(i, k).toString();
                    System.out.println("rowValue = "+model.getValueAt(i, k));
                    String value = "";
                    int z = 0;
                    for(int y = 1; y < rowValue.length(); y++){
                        char c = rowValue.charAt(y);
                        System.out.println("char = "+String.valueOf(c));
                        if(c == ','){
                            tableModel.setValueAt(value, i, z);
                            value = "";
                            z++;
                        } else if(c == ')'){
                            tableModel.setValueAt(value, i, z);
                        }
                        value =  c == ',' ? "" : value.concat(String.valueOf(c));
                        System.out.println("value2 = "+value);
                        
                    }
                 }
            }
           connection.close();
        } catch (Exception e) {
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nommem = new javax.swing.JTextField();
        prenommem = new javax.swing.JTextField();
        cnimem = new javax.swing.JTextField();
        etatcivil = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        statut = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        naissance = new com.toedter.calendar.JDateChooser();
        pacontater = new javax.swing.JTextField();
        addmembre = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numcompte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        motdepasse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genre = new javax.swing.JTextField();
        supprimer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        quitteradmin = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        gestionm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(511, 374));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Noms");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Prenoms");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("N° Carte");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Date De Naissance");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Status Dans L'Association");

        etatcivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marié", "Célibataire", " " }));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Etat Civil");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Personne à Contacter");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_membre", "num_compte", "password", "nom_membre", "prenom_membre", "date_naiss", "num_cni", "etat_civil", "personne_a_contacter", "genre", "statut"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        statut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user", " ", " " }));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Liste Des Membres");

        addmembre.setBackground(new java.awt.Color(0, 0, 204));
        addmembre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addmembre.setText("Ajouter");
        addmembre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addmembreMouseClicked(evt);
            }
        });
        addmembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmembreActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(0, 0, 204));
        modifier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Supprimer");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("id");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("num-compte");

        numcompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numcompteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("passwords");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Genre");

        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });

        supprimer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel12)
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naissance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnimem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etatcivil, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pacontater, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(motdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numcompte, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nommem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prenommem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(27, 27, 27)
                                        .addComponent(statut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(299, 299, 299)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(addmembre)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(modifier)
                        .addGap(67, 67, 67)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70)
                        .addComponent(supprimer)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naissance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numcompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cnimem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(etatcivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(motdepasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pacontater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nommem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(prenommem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(statut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addmembre)
                    .addComponent(modifier)
                    .addComponent(supprimer)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        quitteradmin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        quitteradmin.setText("Quitter");
        quitteradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitteradminActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Consultation");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Prêt");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Gestion Des Comptes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        gestionm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gestionm.setText("Gestion Des Membres");
        gestionm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitteradmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gestionm, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionm)
                .addGap(68, 68, 68)
                .addComponent(jButton6)
                .addGap(67, 67, 67)
                .addComponent(jButton5)
                .addGap(65, 65, 65)
                .addComponent(jButton4)
                .addGap(68, 68, 68)
                .addComponent(quitteradmin)
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitteradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitteradminActionPerformed
       Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        connectionFrame = new Connection();
        connectionFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        connectionFrame.setBounds(d.width/2 - 500/2, d.height/2 - 400/2, 500, 400);
       connectionFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_quitteradminActionPerformed

    private void gestionmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionmActionPerformed
        
    }//GEN-LAST:event_gestionmActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        transactionFrame = new Transaction();
        transactionFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        transactionFrame.setBounds(d.width/2 - 600/2, d.height/2 - 370/2, 600, 370);
       transactionFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
         Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        pretrembourseFrame = new Acceuilpretetrembourcement();
        pretrembourseFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pretrembourseFrame.setBounds(d.width/2 - 600/2, d.height/2 - 370/2, 600, 370);
       pretrembourseFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        connectionFrame = new Connection();
        connectionFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        connectionFrame.setBounds(d.width/2 - 500/2, d.height/2 - 400/2, 500, 400);
       connectionFrame.setVisible(true);
        setVisible(false);      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addmembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmembreActionPerformed
        // TODO add your handling code here:
        naissances = naissance.getDate();
       mynaissance = new java.sql.Date(naissances.getTime());
        
        
       
        try{
             
            PreparedStatement add = connection.prepareStatement("INSERT INTO membre(id_membre,num_compte,passwords,nom_membre,prenom_membre,date_naiss,num_cni,etat_civil,personne_a_contacter,genre,statut) values(?,?,?,?,?,?,?,?,?,?,?)");
            add.setInt(1, Integer.parseInt(id.getText().intern()));
             add.setInt(2, Integer.parseInt(numcompte.getText().intern()));            
              add.setInt(3, Integer.parseInt(motdepasse.getText().intern()));           
            add.setString(4, nommem.getText().intern());
            add.setString(5, prenommem.getText().intern());
            add.setString(6, mynaissance.toGMTString().intern());
            add.setString(7, cnimem.getText().intern());
            add.setString(8, etatcivil.getSelectedItem().toString());
            
             add.setInt(9, Integer.parseInt(pacontater.getText().intern()));
             add.setString(10, genre.getText().intern());
              add.setString(11, statut.getSelectedItem().toString());
               
                 int r = add.executeUpdate();
                 
                 
                 if(r>0){
                     int aj = Integer.parseInt(numcompte.getText().intern());
                     
                 }
            
                 connection.close();
                 Table();
        }catch(Exception e){
             
            
        }
    }//GEN-LAST:event_addmembreActionPerformed

    
    public void Table() {
        String[] member = {"id_membre","num_compte","passwords","nom_membre","prenom_membre","date_naiss","num_cni","etat_civil","personne_a_contacter","genre","statut"};
        String[] afficher = new String[11];
        DefaultTableModel model = new DefaultTableModel(null, member);
        
        try {
             Class.forName("org.postgresql.Driver");
            connection =  DriverManager.getConnection("jdbc:postgresql://"+host+":"+port+"/"+db_name+"", ""+username+"", ""+password+"");
            Statement adds = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = adds.executeQuery("SELECT*FROM membre");
            
            while (rs.next()) {
                afficher[0] = rs.getString("id_membre");
                afficher[1] = rs.getString("num_compte");
                afficher[2] = rs.getString("passwords");
                afficher[3] = rs.getString("nom_membre");
                afficher[4] = rs.getString("prenom_membre");
                afficher[5] = rs.getString("date_naiss");
                afficher[6] = rs.getString("num_cni");
                afficher[7] = rs.getString("etat_civil");
                afficher[8] = rs.getString("personne_a_contacter");
                afficher[9] = rs.getString("genre");
                afficher[10] = rs.getString("statut");
                model.addRow(afficher);
            }
            jTable1.setModel(model);
            connection.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void addmembreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmembreMouseClicked
       naissances = naissance.getDate();
       mynaissance = new java.sql.Date(naissances.getTime());
        
        
       
        try{
             
            PreparedStatement add = connection.prepareStatement("INSERT INTO membre(id_membre,num_compte,passwords,nom_membre,prenom_membre,date_naiss,num_cni,etat_civil,personne_a_contacter,genre,statut) values(?,?,?,?,?,?,?,?,?,?,?)");
            add.setInt(1, Integer.parseInt(id.getText().intern()));
             add.setInt(2, Integer.parseInt(numcompte.getText().intern()));            
              add.setInt(3, Integer.parseInt(motdepasse.getText().intern()));           
            add.setString(4, nommem.getText().intern());
            add.setString(5, prenommem.getText().intern());
            add.setString(6, mynaissance.toGMTString().intern());
            add.setString(7, cnimem.getText().intern());
            add.setString(8, etatcivil.getSelectedItem().toString());
            
             add.setInt(9, Integer.parseInt(pacontater.getText().intern()));
             add.setString(10, genre.getText().intern());
              add.setString(11, statut.getSelectedItem().toString());
               
                 int r = add.executeUpdate();
                 
                 
                 if(r>0){
                     int aj = Integer.parseInt(numcompte.getText().intern());
                     JOptionPane.showMessageDialog(null, "Insertion effectuer avec succes");
                 }
            
                 connection.close();
        }catch(Exception e){
             
            
        }
       
    }//GEN-LAST:event_addmembreMouseClicked

    private void numcompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numcompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numcompteActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
 
        
        
      
        try{
            Class.forName("org.postgresql.Driver");
            connection =  DriverManager.getConnection("jdbc:postgresql://"+host+":"+port+"/"+db_name+"", ""+username+"", ""+password+"");
            Statement adds = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
             
            PreparedStatement add = connection.prepareStatement("UPDATE membre set id_membre= $ ,num_compte= $,passwords= $,nom_membre= $,prenom_membre= $,num_cni= $,etat_civil= $,personne_a_contacter= $,genre=$,statut=$ where id_membre=$");
            add.setInt(1, Integer.parseInt(id.getText().intern()));
             add.setInt(2, Integer.parseInt(numcompte.getText().intern()));            
              add.setInt(3, Integer.parseInt(motdepasse.getText().intern()));           
            add.setString(4, nommem.getText().intern());
            add.setString(5, prenommem.getText().intern());
           
            add.setString(7, cnimem.getText().intern());
            add.setString(8, etatcivil.getSelectedItem().toString());
            
             add.setInt(9, Integer.parseInt(pacontater.getText().intern()));
             add.setString(10, genre.getText().intern());
              add.setString(11, statut.getSelectedItem().toString());
               
                 int r = add.executeUpdate();
                 
                 
                 if(r>0){
                     int aj = Integer.parseInt(numcompte.getText().intern());
                     JOptionPane.showMessageDialog(null, "modification effectuer avec succes");
                 }
            
                 connection.close();
        }catch(Exception e){
             
            
        }
       
    }//GEN-LAST:event_modifierActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       id.setText(model.getValueAt(i, 0).toString());
       numcompte.setText(model.getValueAt(i, 1).toString());
       motdepasse.setText(model.getValueAt(i, 2).toString());
       nommem.setText(model.getValueAt(i, 3).toString());
       prenommem.setText(model.getValueAt(i,4).toString());
       
       cnimem.setText(model.getValueAt(i, 6).toString());
       etatcivil.setSelectedItem(model.getValueAt(i, 7).toString());
       pacontater.setText(model.getValueAt(i, 8).toString());
       genre.setText(model.getValueAt(i, 9).toString());
       statut.setSelectedItem(model.getValueAt(i, 10).toString());
    }//GEN-LAST:event_jTable1MouseReleased

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
         try{
            Class.forName("org.postgresql.Driver");
            connection =  DriverManager.getConnection("jdbc:postgresql://"+host+":"+port+"/"+db_name+"", ""+username+"", ""+password+"");
            Statement adds = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
             
            PreparedStatement add = connection.prepareStatement("DELETE membre from membre where id_membre = $");
            add.setInt(1, Integer.parseInt(id.getText().intern()));
             add.setInt(2, Integer.parseInt(numcompte.getText().intern()));            
              add.setInt(3, Integer.parseInt(motdepasse.getText().intern()));           
            add.setString(4, nommem.getText().intern());
            add.setString(5, prenommem.getText().intern());
           
            add.setString(7, cnimem.getText().intern());
            add.setString(8, etatcivil.getSelectedItem().toString());
            
             add.setInt(9, Integer.parseInt(pacontater.getText().intern()));
             add.setString(10, genre.getText().intern());
              add.setString(11, statut.getSelectedItem().toString());
               
                 int r = add.executeUpdate();
                 
                 
                 if(r>0){
                     int aj = Integer.parseInt(numcompte.getText().intern());
                     JOptionPane.showMessageDialog(null, "suppressio, effectuer avec succes");
                 }
            
                 connection.close();
        }catch(Exception e){
             
            
        }
        
    }//GEN-LAST:event_supprimerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
          String[] member = {"id_membre","num_compte","passwords","nom_membre","prenom_membre","date_naiss","num_cni","etat_civil","personne_a_contacter","genre","statut"};
        String[] afficher = new String[11];
        DefaultTableModel model = new DefaultTableModel(null, member);
        
        try {
             Class.forName("org.postgresql.Driver");
            connection =  DriverManager.getConnection("jdbc:postgresql://"+host+":"+port+"/"+db_name+"", ""+username+"", ""+password+"");
            Statement adds = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = adds.executeQuery("SELECT*FROM membre");
            
            while (rs.next()) {
                afficher[0] = rs.getString("id_membre");
                afficher[1] = rs.getString("num_compte");
                afficher[2] = rs.getString("passwords");
                afficher[3] = rs.getString("nom_membre");
                afficher[4] = rs.getString("prenom_membre");
                afficher[5] = rs.getString("date_naiss");
                afficher[6] = rs.getString("num_cni");
                afficher[7] = rs.getString("etat_civil");
                afficher[8] = rs.getString("personne_a_contacter");
                afficher[9] = rs.getString("genre");
                afficher[10] = rs.getString("statut");
                model.addRow(afficher);
            }
            jTable1.setModel(model);
            connection.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuiladmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Acceuiladmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmembre;
    private javax.swing.JTextField cnimem;
    private javax.swing.JComboBox<String> etatcivil;
    private javax.swing.JTextField genre;
    private javax.swing.JButton gestionm;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField motdepasse;
    private com.toedter.calendar.JDateChooser naissance;
    private javax.swing.JTextField nommem;
    private javax.swing.JTextField numcompte;
    private javax.swing.JTextField pacontater;
    private javax.swing.JTextField prenommem;
    private javax.swing.JButton quitteradmin;
    private javax.swing.JComboBox<String> statut;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
