/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Frida
 */
public class Retrait extends javax.swing.JFrame {

    /**
     * Creates new form Retrait
     */
    String caisse;
    int numero;
    float montant;
    Transaction acceuilFrame;
    public Retrait() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aucunr = new javax.swing.JComboBox<>();
        ncompteretrait = new javax.swing.JTextField();
        montantretrait = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        valideretrait = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Retrait");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Choix Caisse");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 86, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("N° Compte");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 159, 80, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Montant");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 219, 80, -1));

        aucunr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "montant_principale", "montant_epargne", "montant_secours", "montant_ration", "montant_transport", "montant_developpement" }));
        jPanel2.add(aucunr, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 85, 131, -1));
        jPanel2.add(ncompteretrait, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 145, 131, -1));
        jPanel2.add(montantretrait, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 218, 131, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 280, -1, -1));

        valideretrait.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        valideretrait.setText("Validé");
        valideretrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valideretraitActionPerformed(evt);
            }
        });
        jPanel2.add(valideretrait, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 280, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphique/images/dmontant.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 330));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valideretraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valideretraitActionPerformed
         
        java.sql.Connection connection = null;
        String host="localhost";
        String port="5433";
        String db_name="association";
        String username="postgres";
        String password="root";
        boolean veri = false;
         caisse = (String) aucunr.getModel().getSelectedItem();
         caisse.intern();
        try {
            Class.forName("org.postgresql.Driver");
            connection = DriverManager.getConnection("jdbc:postgresql://"+host+":"+port+"/"+db_name+"", ""+username+"", ""+password+"");
            String sql = "SELECT num_compte,"+caisse+" FROM compte ";
            
           Statement statements = connection.createStatement();
           ResultSet resultat = statements.executeQuery(sql);
           numero = Integer.parseInt(ncompteretrait.getText());
           montant = Float.parseFloat(montantretrait.getText());
           while(resultat.next()){
              int num = resultat.getInt("num_compte");
              float c = resultat.getFloat(caisse);
              
              if(numero == num && montant > 0){ 
                  veri= true;
                  c = c - montant;
                  String sqls = "UPDATE compte SET "+caisse+" = "+ c +"WHERE num_compte = "+ num +" ";
                  try{
                  PreparedStatement statement = connection.prepareStatement(sqls);
                  statement.execute();
                  JOptionPane.showMessageDialog(null, "Retrait effectuer avec succes");
                  }catch(Exception e){
                      
                  }
                  }
              }
           
           if(veri == false){
               JOptionPane.showMessageDialog(null, "Compte introuvable ou montant incorect ");
           }
           
                connection.close();
             } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        
        
        
        /*System.out.println("retrait du compte :"+ncompteretrait.getText()+" d'un montant de : "+
                montantretrait.getText()+" dans la caisse "+
                (String)aucunr.getModel().getSelectedItem());*/
    }//GEN-LAST:event_valideretraitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        acceuilFrame = new Transaction();
        acceuilFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        acceuilFrame.setBounds(d.width/2 - 600/2, d.height/2 - 400/2, 600, 400);
       acceuilFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retrait.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retrait().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aucunr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField montantretrait;
    private javax.swing.JTextField ncompteretrait;
    private javax.swing.JButton valideretrait;
    // End of variables declaration//GEN-END:variables
}
